package md2html

import (
	"bytes"
	"fmt"
	"html"
	"path/filepath"
	"strings"

	nethtml "golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// Version is stamped into the provenance marker.
const Version = "v0.1.0"

// MarkerPrefix is the stable portion of the provenance marker. Detection
// matches this prefix only, so files written by older versions are still
// recognized. It carries the full repository URL rather than the bare tool
// name, so output from an unrelated tool also called md2html is never
// mistaken for ours.
const MarkerPrefix = "<!-- generated by https://github.com/AdamF-G/md2html"

// Marker returns the full provenance comment written at the top of every
// generated file.
func Marker() string {
	return fmt.Sprintf("%s %s - edits will be overwritten -->", MarkerPrefix, Version)
}

// extractTitle returns the first <h1>'s text, falling back to the source
// file's base name without extension.
func extractTitle(root *nethtml.Node, sourcePath string) string {
	var found string
	walk(root, func(n *nethtml.Node) {
		if found != "" {
			return
		}
		if n.Type == nethtml.ElementNode && n.DataAtom == atom.H1 {
			if t := strings.TrimSpace(textOf(n)); t != "" {
				found = t
			}
		}
	})
	if found != "" {
		return found
	}
	if sourcePath == "" {
		return "Untitled"
	}
	base := filepath.Base(sourcePath)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// renderPage wraps body in a complete HTML document.
// mermaidCDN is the pinned MermaidJS build a standalone page loads to render
// its diagrams. Pinned rather than floating so a page generated today renders
// the same way next year.
const mermaidCDN = "https://cdn.jsdelivr.net/npm/mermaid@11.17.2/dist/mermaid.esm.min.mjs"

// mermaidRuntime renders diagrams in a standalone page. The goldmark extension
// runs with NoScript, so nothing else loads MermaidJS and a ```mermaid fence
// would otherwise sit on the page as inert preformatted text.
//
// Fragments never get this: they are published as Artifacts, which render
// mermaid natively. The theme test mirrors the stylesheet's two signals —
// an explicit [data-theme] wins, otherwise the OS preference decides.
//
// It also wires up click-to-expand: a diagram rendered at prose width can be
// too small to read, so clicking one clones its SVG into a <dialog> sized
// against the viewport instead of the 68ch measure. showModal() gives this
// Escape-to-close and a backdrop for free; the click listener on the dialog
// itself closes on a backdrop click too, since a click that lands on real
// dialog content targets that content, not the dialog element.
//
// Mermaid's rendered SVG carries width="100%" plus an inline max-width style,
// meant to scale it down inside a narrower container — it has no size of its
// own to resolve "100%" against. A <dialog> defaults to width: fit-content,
// so cloning the SVG as-is collapses both to nothing. The clone gets its
// viewBox dimensions written back as explicit width/height, and the inline
// style stripped, so it has real intrinsic size for the stylesheet's
// max-width/max-height on dialog.mermaid-lightbox svg to scale down from.
const mermaidRuntime = `<script type="module">
import mermaid from "` + mermaidCDN + `";
const explicit = document.documentElement.dataset.theme;
const dark = explicit === "dark" ||
  (explicit !== "light" && matchMedia("(prefers-color-scheme: dark)").matches);
mermaid.initialize({ startOnLoad: true, theme: dark ? "dark" : "default" });

const lightbox = document.createElement("dialog");
lightbox.className = "mermaid-lightbox";
document.body.appendChild(lightbox);
lightbox.addEventListener("click", (e) => {
  if (e.target === lightbox) lightbox.close();
});

document.querySelectorAll("pre.mermaid").forEach((diagram) => {
  diagram.addEventListener("click", () => {
    const original = diagram.querySelector("svg");
    if (!original) return;
    const svg = original.cloneNode(true);
    svg.removeAttribute("style");
    const vb = original.viewBox && original.viewBox.baseVal;
    if (vb && vb.width && vb.height) {
      svg.setAttribute("width", vb.width);
      svg.setAttribute("height", vb.height);
    } else {
      svg.removeAttribute("width");
      svg.removeAttribute("height");
    }
    lightbox.replaceChildren(svg);
    lightbox.showModal();
  });
});
</script>
`

// hasMermaid reports whether the rendered body carries a mermaid diagram. The
// goldmark extension emits <pre class="mermaid">, so the class is the marker.
func hasMermaid(body []byte) bool {
	return bytes.Contains(body, []byte(`class="mermaid"`))
}

func renderPage(body []byte, title, css string) []byte {
	var b strings.Builder
	b.WriteString(Marker())
	b.WriteString("\n<!doctype html>\n<html lang=\"en\">\n<head>\n")
	b.WriteString(`<meta charset="utf-8">` + "\n")
	b.WriteString(`<meta name="viewport" content="width=device-width, initial-scale=1">` + "\n")
	fmt.Fprintf(&b, "<title>%s</title>\n", html.EscapeString(title))
	b.WriteString("<style>\n")
	b.WriteString(css)
	b.WriteString("\n</style>\n</head>\n<body>\n<main>\n")
	b.Write(body)
	b.WriteString("\n</main>\n")
	if hasMermaid(body) {
		b.WriteString(mermaidRuntime)
	}
	b.WriteString("</body>\n</html>\n")
	return []byte(b.String())
}

// renderFragment emits Artifact shape: marker, title, style, then body
// content, with no doctype, html, head or body tags. The Artifact tool
// supplies those itself and scans the first 8 KB for the title, so the
// leading marker comment is harmless.
func renderFragment(body []byte, title, css string) []byte {
	var b strings.Builder
	b.WriteString(Marker())
	b.WriteString("\n")
	fmt.Fprintf(&b, "<title>%s</title>\n", html.EscapeString(title))
	b.WriteString("<style>\n")
	b.WriteString(css)
	b.WriteString("\n</style>\n")
	b.Write(body)
	b.WriteString("\n")
	return []byte(b.String())
}
