package md2html

import (
	"bytes"
	"fmt"
	"html"
	"path/filepath"
	"regexp"
	"strings"

	nethtml "golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// Version is stamped into the provenance marker.
const Version = "v0.5.0"

// MarkerPrefix is the stable portion of the provenance marker. Detection
// matches this prefix only, so files written by older versions are still
// recognized. It carries the full repository URL rather than the bare tool
// name, so output from an unrelated tool also called md2html is never
// mistaken for ours.
const MarkerPrefix = "<!-- generated by https://github.com/AdamF-G/md2html"

// Marker returns the full provenance comment written at the top of every
// generated file.
func Marker() string {
	return fmt.Sprintf("%s %s - edits will be overwritten -->", MarkerPrefix, Version)
}

// extractTitle returns the first <h1>'s text, falling back to the source
// file's base name without extension.
func extractTitle(root *nethtml.Node, sourcePath string) string {
	var found string
	walk(root, func(n *nethtml.Node) {
		if found != "" {
			return
		}
		if n.Type == nethtml.ElementNode && n.DataAtom == atom.H1 {
			if t := strings.TrimSpace(stripChipTokens(textOf(n))); t != "" {
				found = t
			}
		}
	})
	if found != "" {
		return found
	}
	if sourcePath == "" {
		return "Untitled"
	}
	base := filepath.Base(sourcePath)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// mermaidCDN is the pinned MermaidJS build a standalone page loads to render
// its diagrams, and the default for Options.MermaidURL. Pinned rather than
// floating so a page generated today renders the same way next year; a caller
// who needs a different build — one they serve themselves, or a local copy a
// test can reach offline — names it per conversion instead of reassigning
// this.
const mermaidCDN = "https://cdn.jsdelivr.net/npm/mermaid@11.17.2/dist/mermaid.esm.min.mjs"

// mermaidRuntime renders diagrams in a standalone page. The goldmark extension
// runs with NoScript, so nothing else loads MermaidJS and a ```mermaid fence
// would otherwise sit on the page as inert preformatted text.
//
// Fragments never get this: they are published as Artifacts, which render
// mermaid natively. The theme test mirrors the stylesheet's two signals —
// an explicit [data-theme] wins, otherwise the OS preference decides.
//
// It also wires up click-to-expand: a diagram rendered at prose width can be
// too small to read, so clicking one clones its SVG into a <dialog> sized
// against the viewport instead of the 68ch measure. showModal() gives this
// Escape-to-close and a backdrop for free; the click listener on the dialog
// itself closes on a backdrop click too, since a click that lands on real
// dialog content targets that content, not the dialog element.
//
// Mermaid's rendered SVG carries width="100%" plus an inline max-width style,
// meant to scale it down inside a narrower container — it has no size of its
// own to resolve "100%" against. A <dialog> defaults to width: fit-content,
// so cloning the SVG as-is collapses both to nothing. The clone gets its
// viewBox dimensions written back as explicit width/height, and the inline
// style stripped, so it has real intrinsic size for the stylesheet's
// max-width/max-height on dialog.mermaid-lightbox svg to scale down from.
//
// It is a func, not a const, because it embeds the build's URL, which is a
// per-conversion choice: see Options.MermaidURL.
func mermaidRuntime(url string) string {
	return `<script type="module">
import mermaid from "` + url + `";
const explicit = document.documentElement.dataset.theme;
const dark = explicit === "dark" ||
  (explicit !== "light" && matchMedia("(prefers-color-scheme: dark)").matches);
mermaid.initialize({ startOnLoad: true, theme: dark ? "dark" : "default" });

const lightbox = document.createElement("dialog");
lightbox.className = "mermaid-lightbox";
document.body.appendChild(lightbox);
lightbox.addEventListener("click", (e) => {
  if (e.target === lightbox) lightbox.close();
});

document.querySelectorAll("pre.mermaid").forEach((diagram) => {
  diagram.addEventListener("click", () => {
    const original = diagram.querySelector("svg");
    if (!original) return;
    const svg = original.cloneNode(true);
    svg.removeAttribute("style");
    const vb = original.viewBox && original.viewBox.baseVal;
    if (vb && vb.width && vb.height) {
      svg.setAttribute("width", vb.width);
      svg.setAttribute("height", vb.height);
    } else {
      svg.removeAttribute("width");
      svg.removeAttribute("height");
    }
    lightbox.replaceChildren(svg);
    lightbox.showModal();
  });
});
</script>
`
}

// hasMermaid reports whether the rendered body carries a mermaid diagram. The
// goldmark extension emits <pre class="mermaid">, so the class is the marker.
func hasMermaid(body []byte) bool {
	return bytes.Contains(body, []byte(`class="mermaid"`))
}

// mediaExpandRuntime is the click-to-expand counterpart of mermaidRuntime,
// for plain <img> and hand-authored inline <svg>: both get squeezed to the
// 68ch prose measure by the stylesheet's `max-width: 100%`, the same problem
// mermaid diagrams had before they got a lightbox.
//
// Unlike a mermaid diagram, most images and SVGs are already shown at (or
// above) their own size, so wiring every one of them up would put a zoom
// cursor on icons and badges with nothing to zoom into. naturalSize is the
// one place that reads an element's real size — naturalWidth/Height for an
// <img>, viewBox for an <svg> — so an element only becomes expandable when
// that size exceeds its rendered box, and the click handler reuses the same
// value rather than re-deriving it per element type.
//
// An image already wrapped in a link is left alone: the author chose that
// click behavior already. Mermaid's own SVG is also skipped — it lives
// inside pre.mermaid and mermaidRuntime already wires it up; without this
// exclusion a click would bubble into both handlers and open two dialogs.
//
// No CDN needed here, so — unlike mermaidRuntime — this loads on every page
// that has a candidate element, whether or not mermaid is also present.
const mediaExpandRuntime = `<script>
const mediaLightbox = document.createElement("dialog");
mediaLightbox.className = "media-lightbox";
document.body.appendChild(mediaLightbox);
mediaLightbox.addEventListener("click", (e) => {
  if (e.target === mediaLightbox) mediaLightbox.close();
});

function naturalSize(el) {
  if (el.tagName === "IMG") {
    return el.naturalWidth && el.naturalHeight
      ? { width: el.naturalWidth, height: el.naturalHeight }
      : null;
  }
  const vb = el.viewBox && el.viewBox.baseVal;
  return vb && vb.width && vb.height ? { width: vb.width, height: vb.height } : null;
}

function wireExpand(el) {
  const size = naturalSize(el);
  const box = el.getBoundingClientRect();
  if (!size || size.width <= box.width) return;
  el.classList.add("expandable");
  el.addEventListener("click", () => {
    const clone = el.cloneNode(true);
    clone.removeAttribute("style");
    clone.setAttribute("width", size.width);
    clone.setAttribute("height", size.height);
    mediaLightbox.replaceChildren(clone);
    mediaLightbox.showModal();
  });
}

document.querySelectorAll("img, svg").forEach((el) => {
  if (el.closest("a") || el.closest("pre.mermaid")) return;
  if (el.tagName === "IMG" && !el.complete) {
    el.addEventListener("load", () => wireExpand(el));
  } else {
    wireExpand(el);
  }
});
</script>
`

// hasExpandableMedia reports whether the rendered body carries a plain
// <img> or a hand-authored inline <svg>. A mermaid diagram doesn't count:
// at this point its <pre class="mermaid"> still holds raw diagram text —
// MermaidJS only inserts an <svg> client-side, after this check has run.
func hasExpandableMedia(body []byte) bool {
	return bytes.Contains(body, []byte("<img")) || bytes.Contains(body, []byte("<svg"))
}

// renderPage wraps body in a complete HTML document. mermaidURL is the
// build the mermaid runtime imports, and is only consulted for a body that
// actually carries a diagram.
func renderPage(body []byte, title, lang, css, mermaidURL string) []byte {
	var b strings.Builder
	b.WriteString(Marker())
	fmt.Fprintf(&b, "\n<!doctype html>\n<html lang=\"%s\">\n<head>\n", html.EscapeString(lang))
	b.WriteString(`<meta charset="utf-8">` + "\n")
	b.WriteString(`<meta name="viewport" content="width=device-width, initial-scale=1">` + "\n")
	fmt.Fprintf(&b, "<title>%s</title>\n", html.EscapeString(title))
	b.WriteString("<style>\n")
	b.WriteString(css)
	b.WriteString("\n</style>\n</head>\n<body>\n<main>\n")
	b.Write(body)
	b.WriteString("\n</main>\n")
	if hasMermaid(body) {
		b.WriteString(mermaidRuntime(mermaidURL))
	}
	if hasExpandableMedia(body) {
		b.WriteString(mediaExpandRuntime)
	}
	b.WriteString("</body>\n</html>\n")
	return []byte(b.String())
}

// renderFragment emits Artifact shape: marker, title, style, then body
// content, with no doctype, html, head or body tags. The Artifact tool
// supplies those itself and scans the first 8 KB for the title, so the
// leading marker comment is harmless.
func renderFragment(body []byte, title, css string) []byte {
	var b strings.Builder
	b.WriteString(Marker())
	b.WriteString("\n")
	fmt.Fprintf(&b, "<title>%s</title>\n", html.EscapeString(title))
	b.WriteString("<style>\n")
	b.WriteString(css)
	b.WriteString("\n</style>\n")
	b.Write(body)
	b.WriteString("\n")
	return []byte(b.String())
}

// langTag is the shape of a BCP 47 language tag: a primary subtag of two to
// eight letters, or the single-letter x (private use) or i (grandfathered),
// then any number of hyphenated subtags of one to eight letters or digits.
// It checks shape, not registry membership — "qq" passes — because the
// point is to catch a typo like en_US or a stray sentence, not to ship the
// IANA registry.
var langTag = regexp.MustCompile(`^(?:[A-Za-z]{2,8}|[xXiI])(?:-[A-Za-z0-9]{1,8})*$`)

// IsLangTag reports whether s is shaped like a BCP 47 language tag, the
// check Options.Lang is held to. It is exported so a caller taking a
// language from its own user, as the CLI's --lang does, can refuse a bad
// one up front instead of getting a warning per document.
func IsLangTag(s string) bool { return langTag.MatchString(s) }

// pageLang picks a page's language: the document's front matter, then the
// run-wide option, then English. An unusable value is reported and passed
// over rather than written, so a typo costs a warning, not a page that
// claims a language no reader supports.
func pageLang(front, opt string, warn func(string)) string {
	for _, c := range []struct{ val, from string }{
		{front, "front matter lang"},
		{opt, "Lang option"},
	} {
		if c.val == "" {
			continue
		}
		if IsLangTag(c.val) {
			return c.val
		}
		if warn != nil {
			warn(fmt.Sprintf("%s %q is not a language tag (such as en or pt-BR); ignoring it", c.from, c.val))
		}
	}
	return "en"
}
