package md2html

import (
	"os"
	"path/filepath"
	"testing"
)

func TestSafeWriteCreatesNewFile(t *testing.T) {
	p := filepath.Join(t.TempDir(), "new.html")
	res, err := SafeWrite(p, []byte(Marker()+"\n<p>x</p>"))
	if err != nil {
		t.Fatalf("SafeWrite: %v", err)
	}
	if res != WriteCreated {
		t.Errorf("got %v, want WriteCreated", res)
	}
}

func TestSafeWriteCreatesParentDirectories(t *testing.T) {
	p := filepath.Join(t.TempDir(), "a", "b", "c.html")
	if _, err := SafeWrite(p, []byte(Marker())); err != nil {
		t.Fatalf("SafeWrite: %v", err)
	}
	if _, err := os.Stat(p); err != nil {
		t.Errorf("file not created: %v", err)
	}
}

func TestSafeWriteOverwritesOurOwnOutput(t *testing.T) {
	p := filepath.Join(t.TempDir(), "ours.html")
	os.WriteFile(p, []byte(Marker()+"\n<p>old</p>"), 0o644)
	res, err := SafeWrite(p, []byte(Marker()+"\n<p>new</p>"))
	if err != nil {
		t.Fatalf("SafeWrite: %v", err)
	}
	if res != WriteOverwritten {
		t.Errorf("got %v, want WriteOverwritten", res)
	}
	b, _ := os.ReadFile(p)
	if string(b) != Marker()+"\n<p>new</p>" {
		t.Errorf("content not replaced: %s", b)
	}
}

func TestSafeWriteRefusesHandWrittenFile(t *testing.T) {
	p := filepath.Join(t.TempDir(), "theirs.html")
	original := "<html><body>hand written</body></html>"
	os.WriteFile(p, []byte(original), 0o644)
	res, err := SafeWrite(p, []byte(Marker()+"\n<p>new</p>"))
	if err != nil {
		t.Fatalf("SafeWrite returned error, want refusal result: %v", err)
	}
	if res != WriteRefused {
		t.Errorf("got %v, want WriteRefused", res)
	}
	b, _ := os.ReadFile(p)
	if string(b) != original {
		t.Errorf("refused file was modified: %s", b)
	}
}

// An older version's marker must still be recognized as ours.
func TestIsOursMatchesAcrossVersions(t *testing.T) {
	p := filepath.Join(t.TempDir(), "old.html")
	os.WriteFile(p, []byte(MarkerPrefix+" v0.0.1 - edits will be overwritten -->\n<p>x</p>"), 0o644)
	ok, err := IsOurs(p)
	if err != nil {
		t.Fatalf("IsOurs: %v", err)
	}
	if !ok {
		t.Error("older version marker not recognized as ours")
	}
}

// Output from an unrelated tool that happens to be called md2html must NOT
// be claimed. This is why the marker carries the full repo URL.
func TestIsOursRejectsForeignToolOfSameName(t *testing.T) {
	p := filepath.Join(t.TempDir(), "foreign.html")
	os.WriteFile(p, []byte("<!-- generated by md2html 3.1 -->\n<p>x</p>"), 0o644)
	ok, err := IsOurs(p)
	if err != nil {
		t.Fatalf("IsOurs: %v", err)
	}
	if ok {
		t.Error("claimed a foreign tool's output")
	}
}

// Detection reads only the first 512 bytes; a marker beyond that is not ours.
func TestIsOursIgnoresMarkerBeyond512Bytes(t *testing.T) {
	p := filepath.Join(t.TempDir(), "late.html")
	padding := make([]byte, 600)
	for i := range padding {
		padding[i] = ' '
	}
	os.WriteFile(p, append(padding, []byte(Marker())...), 0o644)
	ok, _ := IsOurs(p)
	if ok {
		t.Error("matched a marker beyond the 512-byte window")
	}
}
