// Command md2html converts Markdown documentation trees to HTML.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"runtime"
	"strings"
	"sync"

	"github.com/AdamF-G/md2html"
)

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

// stringList is a flag.Value collecting a repeatable, comma-separable
// option. Both spellings are accepted — "--exclude a --exclude b" and
// "--exclude a,b" — because supporting only one reliably produces a
// directory named "a,b" or a second flag that is silently ignored.
type stringList []string

func (l *stringList) String() string { return strings.Join(*l, ",") }

func (l *stringList) Set(v string) error {
	for _, part := range strings.Split(v, ",") {
		if p := strings.TrimSpace(part); p != "" {
			*l = append(*l, p)
		}
	}
	return nil
}

// run is the testable entry point. It returns the process exit code.
//
// stdout is currently unused: md2html always writes files, never streams
// HTML. The parameter is retained so tests capture both streams and so a
// future --stdout mode needs no signature change. Name it _ if your linter
// objects.
func run(args []string, stdout, stderr io.Writer) int {
	_ = stdout
	fs := flag.NewFlagSet("md2html", flag.ContinueOnError)
	fs.SetOutput(stderr)
	fs.Usage = func() {
		fmt.Fprint(stderr, `md2html - convert Markdown docs to HTML

Usage:
  md2html [flags] <entry> [entry...]

Entries may be files or directories, and several may be given in one run:
the emit set is their union, so an extra directory can be built for a
single invocation without being added to a standing entry list. Links
between documents are followed across directories, without limit unless
--link-depth says otherwise, and never into an --exclude'd directory.
Output never leaves -o.

Flags:
`)
		fs.PrintDefaults()
	}

	var (
		outDir   = fs.String("o", "", "output directory (default: write beside each source)")
		depth    = fs.Int("depth", -1, "directory levels to seed from a directory entry (-1 unlimited)")
		fragment = fs.Bool("fragment", false, "emit Artifact-shaped fragments instead of full pages")
		cssPath  = fs.String("css", "", "replace the embedded stylesheet with this file")
		noTable  = fs.Bool("no-table-scroll", false, "do not wrap tables in a scroll container")
		noAnchor = fs.Bool("no-anchors", false, "do not add heading anchors")
		noExt    = fs.Bool("no-external-links", false, "do not mark external links")
		noMd     = fs.Bool("no-md-links", false, "do not rewrite .md links")
		noAssets = fs.Bool("no-assets", false, "do not rewrite asset links")
	)
	var exclude stringList
	fs.Var(&exclude, "exclude", "directory prefix never to enter or write to (repeatable, comma-separated)")
	// Go's flag package stops parsing at the first positional argument, so a
	// plain fs.Parse would read "md2html ./docs -o ./site" as three entry
	// points. Resume parsing after each positional so flags may appear
	// anywhere, which is what every documented invocation does.
	var entries []string
	for {
		if err := fs.Parse(args); err != nil {
			return 2
		}
		if fs.NArg() == 0 {
			break
		}
		entries = append(entries, fs.Arg(0))
		args = fs.Args()[1:]
	}
	if len(entries) == 0 {
		fs.Usage()
		return 2
	}

	var css string
	if *cssPath != "" {
		b, err := os.ReadFile(*cssPath)
		if err != nil {
			fmt.Fprintf(stderr, "md2html: --css: %v\n", err)
			return 1
		}
		css = string(b)
	}

	res, err := md2html.Crawl(md2html.CrawlOptions{
		Entries:   entries,
		OutDir:    *outDir,
		Depth:     *depth,
		Exclude:   exclude,
		NoMdLinks: *noMd,
		NoAssets:  *noAssets,
	})
	if err != nil {
		fmt.Fprintf(stderr, "md2html: %v\n", err)
		return 1
	}

	type outcome struct {
		src string
		res md2html.WriteResult
		err error
	}
	results := make([]outcome, len(res.Docs))

	var wg sync.WaitGroup
	sem := make(chan struct{}, runtime.NumCPU())
	for i := range res.Docs {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			d := res.Docs[i]
			src, err := os.ReadFile(d.Src)
			if err != nil {
				results[i] = outcome{d.Src, md2html.WriteRefused, err}
				return
			}
			out, err := md2html.Convert(src, buildOptions(d, *fragment, css,
				*noTable, *noAnchor, *noExt))
			if err != nil {
				results[i] = outcome{d.Src, md2html.WriteRefused, err}
				return
			}
			wr, err := md2html.SafeWrite(d.Out, out)
			results[i] = outcome{d.Src, wr, err}
		}(i)
	}
	wg.Wait()

	written, refused, failed := 0, 0, 0
	for i, o := range results {
		switch {
		case o.err != nil:
			failed++
			fmt.Fprintf(stderr, "md2html: %s: %v\n", o.src, o.err)
		case o.res == md2html.WriteRefused:
			refused++
			fmt.Fprintf(stderr, "md2html: refusing to overwrite %s (not generated by md2html)\n",
				res.Docs[i].Out)
		default:
			written++
		}
	}
	for _, w := range res.Warnings {
		fmt.Fprintf(stderr, "md2html: %s: %s\n", w.Src, w.Message)
	}
	if len(res.External) > 0 {
		fmt.Fprintf(stderr, "md2html: pulled in %d document(s) from outside %s\n",
			len(res.External), res.Base)
		for _, e := range res.External {
			fmt.Fprintf(stderr, "md2html:   %s\n", e)
		}
	}
	fmt.Fprintf(stderr, "md2html: %d written, %d refused, %d failed, %d warning(s)\n",
		written, refused, failed, len(res.Warnings))

	if refused > 0 || failed > 0 {
		return 1
	}
	return 0
}

// buildOptions assembles per-document conversion options from the flags.
func buildOptions(d md2html.Doc, fragment bool, css string,
	noTable, noAnchor, noExt bool) md2html.Options {

	var ts []md2html.Transform
	if !noTable {
		ts = append(ts, md2html.TableScroll())
	}
	if !noAnchor {
		ts = append(ts, md2html.HeadingAnchors())
	}
	if !noExt {
		ts = append(ts, md2html.ExternalLinks())
	}

	return md2html.Options{
		Fragment:   fragment,
		SourcePath: d.Src,
		CSS:        css,
		Transforms: ts,
		LinkMap:    d.LinkMap,
	}
}
